version: "3.7"
services:
  nginx:
    image: 'asucrews/nginx-more:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: volume
        source: nginx_libs
        target: /var/lib/nginx
      - type: volume
        source: nginx_logs
        target: /var/log/nginx
volumes:
  nginx_libs:
  nginx_logs:
